name: "✍ Report a Typo"
description: "Report a typo you encountered with text on the website"
title: "✍ Typo: <short description of the typo>"
labels:
  - "type: typo"
body:
  - attributes:
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      label: Typo Report Checklist
      options:
        - label: I have searched the word or phrase in question online to verify it's incorrect.
          required: true
        - label: This is the appropriate issue form for the typo I would like to report.
          required: true
    type: checkboxes
  - attributes:
      value: |
        If this report is for a small typo you're sure is a mistake,
        feel free to instead send a pull request directly.
    type: markdown
  - attributes:
      description: Which page within which site contains the typo?
      label: Impacted Site Page
    type: textarea
    validations:
      required: true
  - attributes:
      description: In detail, what is wrong with the page's text?
      label: What's Wrong?
    type: textarea
    validations:
      required: true
  - attributes:
      label: Additional Info
      description: Any additional info you'd like to provide.
    type: textarea
