blank_issues_enabled: false
contact_links:
  - about: |
      This issue tracker is specifically for the website on learningtypescript.com.
      It pulls project content from github.com/LearningTypeScript/projects.
      Go here to report an issue with a project.
    name: Looking for the Projects Issue Tracker?
    url: https://github.com/JoshuaKGoldberg/learning-typescript
